// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';


var Button = 0;

var Section = 0;

var Paragraph = 0;

exports.Button = Button;
exports.Section = Section;
exports.Paragraph = Paragraph;
/* No side effect */
