// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';


var Button = 0;

var Container = 0;

var Paragraph = 0;

var Section = 0;

exports.Button = Button;
exports.Container = Container;
exports.Paragraph = Paragraph;
exports.Section = Section;
/* No side effect */
